"""Оркестратор: собирает все шаги для одного клипа в финальный MP4.

Progress API
------------
progress_cb(event: dict) вызывается с такими событиями:

  {"type": "stage", "stage": "<id>", "label": "<человеческое описание>",
   "pct_overall": float}

  {"type": "substage", "stage": "<id>", "label": "...",
   "pct_overall": float, "pct_substage": float,
   "extra": {"position_sec": ..., "total_sec": ..., "speed_x": ..., "eta_sec": ...}}

  {"type": "clip_start", "i": int, "n": int, "title": "...", "pct_overall": float}
  {"type": "clip_substep", "i": int, "step": "cut|reframe|subtitle|audio", ...}
  {"type": "clip_done", "i": int, "title": "...", "file": "...", "duration": ...}
  {"type": "clip_failed", "i": int, "title": "...", "reason": "..."}
  {"type": "done", "meta": {...}}
  {"type": "error", "message": "..."}

Этапы (`stage` id и их вес в общем прогрессе):
  ingest      0  →  3   %
  extract     3  →  10  %
  transcribe  10 →  55  %
  analyze     55 →  60  %
  clips       60 →  98  %
  finalize    98 →  100 %
"""

from __future__ import annotations

import json
import shutil
import time
import uuid
from dataclasses import replace
from pathlib import Path
from typing import Callable

from .analyze import Segment, analyze
from .audio_mix import mix_with_music, pick_music
from .vocal_isolation import isolate_vocals
from .color_grade import apply_color_grade
from .cut import cut_segment
from .ingest import ingest, ingest_many
from .reframe import reframe
from .seo_generator import generate_seo
from .silence_cut import remove_silences
from .subtitle import build_ass, burn_subtitles
from .transcribe import (
    TranscribeProgress,
    resolve_source_for_time,
    transcribe,
    transcribe_many,
)
from .utils import get_logger, load_config
from .youtube_upload import (
    AuthRequired,
    QuotaExceeded,
    UploadResult,
    is_authorized as yt_is_authorized,
    upload_clip as yt_upload_clip,
)
from .tiktok_upload import (
    AuthRequired as TikTokAuthRequired,
    TikTokUploadResult,
    adapt_metadata_for_tiktok,
    is_authorized as tt_is_authorized,
    upload_clip as tt_upload_clip,
)

log = get_logger("render")


def _wait_for_music_choice(
    decision_file: str | None,
    variants: list,
    timeout_sec: int = 1200,
) -> Path | None:
    """Поллит decision.json пока пользователь не выберет вариант или скип.

    decision.json формат: {"music_index": 1|2|3} или {"music_index": null} для пропуска.
    """
    if not decision_file:
        # decision-файл не настроен — просто берём первый вариант автоматом
        return variants[0].path if variants else None

    df = Path(decision_file)
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        if df.exists():
            try:
                data = json.loads(df.read_text(encoding="utf-8"))
                idx = data.get("music_index")
                if idx is None:
                    return None  # пользователь нажал "пропустить музыку"
                for v in variants:
                    if v.index == idx:
                        return v.path
                log.warning(f"music_index={idx} не нашёлся в вариантах")
                return None
            except (json.JSONDecodeError, OSError):
                pass
        time.sleep(1.0)
    log.warning(f"Таймаут {timeout_sec}с ожидания выбора музыки")
    return None


# Веса этапов в общем прогрессе (сумма = 100)
def _music_rights_info(
    music_to_use: Path | None,
    chosen_music: Path | None,
    mood: str,
    cfg: dict,
) -> tuple[dict, bool, str]:
    if not music_to_use:
        return (
            {
                "source_type": "none",
                "file": None,
                "mood": mood,
                "license_status": "no_background_music",
            },
            False,
            "Background music was not added. Auto subtitles/reframing do not make the audio AI-generated.",
        )

    music_path = Path(music_to_use)
    is_ai_generated = bool(chosen_music and music_path == Path(chosen_music))

    if is_ai_generated:
        backend = (cfg.get("music") or {}).get("backend", "unknown")
        return (
            {
                "source_type": "ai_generated",
                "backend": backend,
                "file": music_path.name,
                "path": str(music_path),
                "mood": mood,
                "license_status": "ai_generated_safe",
            },
            True,
            f"Background music was generated by the configured music backend ({backend}).",
        )

    return (
        {
            "source_type": "user_library",
            "file": music_path.name,
            "path": str(music_path),
            "mood": mood,
            "license_status": "user_provided_unverified",
            "note": "Track came from the local music folder; verify its license before publishing.",
        },
        False,
        "Background music came from the local music folder, not from AI generation.",
    )


_STAGE_RANGES = {
    "ingest":     (0, 3),
    "extract":    (3, 10),
    "transcribe": (10, 50),
    "analyze":    (50, 55),
    "music":      (55, 65),   # генерация AI-музыки + выбор пользователем
    "clips":      (65, 98),
    "finalize":   (98, 100),
}


def _map_stage_pct(stage: str, local_pct: float) -> float:
    """Маппит локальный % этапа (0-100) в общий % проекта."""
    lo, hi = _STAGE_RANGES.get(stage, (0, 100))
    return lo + (hi - lo) * (local_pct / 100.0)


def run_job(
    source: "str | list[str]",
    reframe_mode: str = "blur",
    add_subtitles: bool = True,
    add_music: bool = True,
    progress_cb: Callable[[dict], None] | None = None,
    clips_count: int | None = None,
    target_duration: int | None = None,
    subtitle_overrides: dict | None = None,
    smart_zoom_out: float | None = None,
    youtube_upload: bool = False,
    youtube_privacy: str = "unlisted",
    youtube_source_context: str = "",
    tiktok_upload: bool = False,
    tiktok_privacy: str = "SELF_ONLY",
    tiktok_disable_comment: bool = False,
    tiktok_disable_duet: bool = False,
    tiktok_disable_stitch: bool = False,
    tiktok_is_aigc: bool = False,
    cut_silences: bool = True,
    silence_min_sec: float = 0.5,
    silence_threshold_db: float = -30.0,
    silence_padding_sec: float = 0.12,
    color_grade: bool = True,
    generate_music: bool = False,
    music_duration_sec: float = 30.0,
    music_n_variants: int = 3,
    music_custom_hint: str = "",
    music_decision_file: str | None = None,
    music_wait_timeout_sec: int = 1800,
    music_volume: float | None = None,
    music_lora_repo: str | None = None,
    music_lora_weight: float = 0.0,
) -> dict:
    cfg = load_config()

    if clips_count is not None:
        cfg["shorts"]["clips_per_video"] = clips_count
    if target_duration is not None:
        cfg["shorts"]["target_duration_sec"] = target_duration
    if smart_zoom_out is not None:
        cfg.setdefault("reframe", {})["smart_zoom_out"] = smart_zoom_out

    if subtitle_overrides:
        sub = cfg.setdefault("subtitle", {})
        for k, v in subtitle_overrides.items():
            if v is not None:
                sub[k] = v

    job_id = uuid.uuid4().hex[:10]
    out_dir = Path(cfg["paths"]["output"]) / job_id
    shorts_dir = out_dir / "shorts"
    debug_dir = out_dir / "debug"
    shorts_dir.mkdir(parents=True, exist_ok=True)
    debug_dir.mkdir(parents=True, exist_ok=True)
    cfg["_debug_dir"] = str(debug_dir)

    job_start = time.monotonic()

    def emit(event: dict) -> None:
        if progress_cb:
            try:
                progress_cb(event)
            except Exception:  # noqa: BLE001 — UI не должен убивать pipeline
                pass

    def stage(stage_id: str, label: str, local_pct: float = 0.0) -> None:
        pct_overall = _map_stage_pct(stage_id, local_pct)
        log.info(f"[{stage_id}] {label} ({pct_overall:.0f}%)")
        emit({
            "type": "stage",
            "stage": stage_id,
            "label": label,
            "pct_overall": round(pct_overall, 1),
            "elapsed_sec": round(time.monotonic() - job_start, 1),
        })

    def substage(stage_id: str, label: str, local_pct: float, extra: dict | None = None) -> None:
        pct_overall = _map_stage_pct(stage_id, local_pct)
        emit({
            "type": "substage",
            "stage": stage_id,
            "label": label,
            "pct_overall": round(pct_overall, 1),
            "pct_substage": round(local_pct, 1),
            "elapsed_sec": round(time.monotonic() - job_start, 1),
            "extra": extra or {},
        })

    try:
        # === ШАГ 1: Ingest (single или multi) ===
        sources_list: list[str] = [source] if isinstance(source, str) else list(source)
        if not sources_list:
            raise RuntimeError("Не передано ни одного источника видео")

        is_multi = len(sources_list) > 1
        stage("ingest",
              f"Принимаю {len(sources_list)} видео" if is_multi else "Принимаю исходное видео")
        videos = ingest_many(sources_list, Path(cfg["paths"]["cache"]))
        # video — главное (первое); video_boundaries покрывает все источники
        video = videos[0]
        stage("ingest",
              f"Видео готово: {len(videos)} файл(ов), главный={video.name}", 100)

        # === ШАГ 2-3: Извлечение аудио + транскрипция ===
        def _transcribe_cb(t_stage: str, payload) -> None:
            if t_stage == "extract_audio":
                substage("extract", "Извлекаю аудиодорожку (моно 16кГц)",
                         float(payload), extra={"position_pct": payload})
            elif t_stage == "transcribe" and isinstance(payload, TranscribeProgress):
                substage(
                    "transcribe",
                    f"Транскрибирую: {payload.position_sec:.0f}/{payload.total_sec:.0f}с",
                    payload.pct,
                    extra={
                        "position_sec": round(payload.position_sec, 1),
                        "total_sec": round(payload.total_sec, 1),
                        "segments_done": payload.segments_done,
                        "speed_x": round(payload.speed_x, 2),
                        "eta_sec": round(payload.eta_sec, 1),
                        "elapsed_sec": round(payload.elapsed_sec, 1),
                    },
                )
            elif t_stage == "cache_hit":
                stage("transcribe", "Транскрипт найден в кеше", 100)

        stage("extract", "Готовлю аудио для транскрипции")
        transcript = transcribe_many(
            videos, Path(cfg["paths"]["cache"]), cfg, progress_cb=_transcribe_cb
        )
        stage("transcribe",
              f"Транскрипт готов: {len(transcript.get('segments', []))} сегментов "
              f"из {len(videos)} видео", 100)

        # === ШАГ 4: Анализ через LLM ===
        stage("analyze", "Анализирую интересные моменты через LLM")
        segments = analyze(transcript, cfg)
        if not segments:
            raise RuntimeError("LLM не вернул ни одного сегмента")

        # --- Валидация таймстампов ---
        all_segs = transcript.get("segments", [])
        video_duration = transcript.get("duration") or (all_segs[-1]["end"] if all_segs else 0)

        if video_duration > 0:
            # MMSS→секунды эвристика (если start выходит за пределы)
            out_of_bounds = sum(1 for s in segments if s.start >= video_duration)
            if out_of_bounds > 0:
                log.warning(
                    f"{out_of_bounds}/{len(segments)} сегментов за пределами видео "
                    f"({video_duration:.0f}с). Пробую конвертировать MMSS→секунды"
                )
                for seg in segments:
                    if seg.start >= video_duration:
                        mm = int(seg.start) // 100
                        ss = int(seg.start) % 100
                        new_start = mm * 60 + ss
                        mm2 = int(seg.end) // 100
                        ss2 = int(seg.end) % 100
                        new_end = mm2 * 60 + ss2
                        if 0 <= new_start < video_duration and new_end > new_start:
                            log.info(
                                f"  Конвертировано: {seg.title} "
                                f"[{seg.start:.0f}-{seg.end:.0f}] → "
                                f"[{new_start}-{new_end}]"
                            )
                            seg.start = float(new_start)
                            seg.end = float(new_end)

            valid_segments: list[Segment] = []
            min_dur = cfg["shorts"]["min_duration_sec"]
            max_dur = cfg["shorts"]["max_duration_sec"]
            target = cfg["shorts"]["target_duration_sec"]
            target_floor = max(
                min_dur,
                target * float(cfg["shorts"].get("target_min_ratio", 0.8)),
            )

            for seg in segments:
                if seg.start < 0:
                    seg.start = 0.0
                if seg.start >= video_duration:
                    log.warning(
                        f"Сегмент '{seg.title}' за пределами видео, пропускаю"
                    )
                    continue
                if seg.end > video_duration:
                    seg.end = video_duration
                seg_dur = seg.end - seg.start
                if seg_dur < target_floor:
                    seg.end = min(seg.start + target, video_duration)
                    seg_dur = seg.end - seg.start
                    if seg_dur < target_floor:
                        log.warning(f"Клип '{seg.title}' слишком короткий, пропускаю")
                        continue
                elif seg_dur > max_dur:
                    log.warning(
                        f"Клип '{seg.title}' длинный ({seg_dur:.0f}с), обрезаю до {max_dur}с"
                    )
                    seg.end = seg.start + max_dur
                valid_segments.append(seg)

            valid_segments.sort(key=lambda s: s.start)
            non_overlapping: list[Segment] = []
            for seg in valid_segments:
                if non_overlapping and seg.start < non_overlapping[-1].end:
                    log.warning(f"Клип '{seg.title}' пересекается, пропускаю")
                    continue
                non_overlapping.append(seg)
            segments = non_overlapping

            # Multi-source: отбрасываем сегменты пересекающие границы видео
            boundaries_check = transcript.get("video_boundaries") or []
            if len(boundaries_check) > 1:
                cleaned: list[Segment] = []
                for seg in segments:
                    src_a, _ = resolve_source_for_time(seg.start, boundaries_check)
                    src_b, _ = resolve_source_for_time(
                        max(seg.start, seg.end - 0.001), boundaries_check
                    )
                    if src_a != src_b:
                        # Пробуем clip к концу первого видео
                        for b in boundaries_check:
                            if Path(b["path"]) == src_a:
                                new_end_global = b["offset"] + b["duration"]
                                seg.end = new_end_global
                                if seg.end - seg.start >= target_floor:
                                    cleaned.append(seg)
                                else:
                                    log.warning(
                                        f"Клип '{seg.title}' пересекал границу "
                                        f"видео — после обрезки слишком короткий, "
                                        f"пропускаю"
                                    )
                                break
                    else:
                        cleaned.append(seg)
                segments = cleaned

            if not segments:
                raise RuntimeError(
                    f"Все сегменты от LLM за пределами видео ({video_duration:.0f}с)"
                )
            expected_count = int(cfg["shorts"].get("clips_per_video", len(segments)))
            if (
                len(segments) < expected_count
                and not cfg["shorts"].get("allow_fewer_clips", False)
            ):
                raise RuntimeError(
                    f"После валидации осталось {len(segments)}/{expected_count} клипов. "
                    "Перезапусти анализ или ослабь allow_fewer_clips."
                )

        stage("analyze", f"LLM выбрал {len(segments)} моментов", 100)

        # Уведомляем UI о плане работ — какие клипы будут собираться
        emit({
            "type": "plan",
            "clips": [
                {
                    "i": i + 1,
                    "title": s.title,
                    "start": s.start,
                    "end": s.end,
                    "duration": round(s.end - s.start, 1),
                    "music_mood": s.music_mood,
                }
                for i, s in enumerate(segments)
            ],
        })

        # === ШАГ 4.5: Генерация музыки (опционально) ===
        # Если включено — генерим 3 варианта, ждём выбора пользователя
        # через decision-файл, потом применяем выбранный трек ко всем клипам.
        chosen_music: Path | None = None
        if generate_music:
            from .music_gen import (
                generate_variants, is_model_available, unload_pipeline,
            )
            ok, reason = is_model_available()
            if not ok:
                log.warning(f"Музыкальная модель недоступна: {reason}")
                emit({"type": "music_skipped", "reason": reason})
            else:
                # Доминирующее настроение среди клипов
                from collections import Counter
                mood = Counter(s.music_mood for s in segments).most_common(1)[0][0]
                music_dir = out_dir / "music_variants"

                # Авто-длина: ровно как самый длинный клип (плюс маленький buffer).
                # Stable Audio Open нативно умеет до 47с — ограничиваем.
                # Если клип длиннее, музыка зациклится через aloop в audio_mix.
                longest_clip = max((s.end - s.start) for s in segments)
                effective_duration = min(round(longest_clip + 1.0, 1), 47.0)
                log.info(
                    f"Авто-длина музыки: {effective_duration}с "
                    f"(самый длинный клип: {longest_clip:.1f}с)"
                )

                stage(
                    "music",
                    f"Генерирую {music_n_variants} вариантов музыки ({mood}, {effective_duration}с)",
                    0,
                )

                def _mg_cb(stg: str, pct: float) -> None:
                    emit({"type": "music_progress", "stage": stg, "pct": pct})

                variants = generate_variants(
                    music_dir,
                    mood=mood,
                    duration_sec=effective_duration,
                    n_variants=music_n_variants,
                    custom_hint=music_custom_hint,
                    progress_cb=_mg_cb,
                    lora_repo=music_lora_repo,
                    lora_weight=music_lora_weight,
                )
                # Освобождаем VRAM перед рендером клипов
                unload_pipeline()

                stage("music", f"Готово: {len(variants)} вариантов, жду выбор пользователя", 100)
                emit({
                    "type": "music_pick_required",
                    "variants": [
                        {
                            "index": v.index,
                            "path": str(v.path),
                            "preview_path": str(v.preview_path),
                            "mood": v.mood,
                            "duration_sec": v.duration_sec,
                            "prompt": v.prompt,
                        }
                        for v in variants
                    ],
                    "decision_file": music_decision_file,
                })

                # Ждём пока UI запишет decision.json с выбранным индексом
                chosen_music = _wait_for_music_choice(
                    music_decision_file, variants, music_wait_timeout_sec
                )
                if chosen_music:
                    log.info(f"Пользователь выбрал музыку: {chosen_music.name}")
                    emit({"type": "music_picked", "path": str(chosen_music)})
                else:
                    log.warning("Музыка не выбрана (таймаут/пропуск) — рендерим без неё")
                    emit({"type": "music_skipped", "reason": "no choice"})

        # === ШАГ 5: Рендер клипов ===
        music_dir = Path(cfg["paths"]["music"])
        clip_results: list[dict] = []
        failed: list[dict] = []
        n = len(segments)

        for i, seg in enumerate(segments):
            clip_local_pct = (i / n) * 100
            stage("clips", f"Клип {i + 1}/{n}: {seg.title}", clip_local_pct)
            emit({
                "type": "clip_start",
                "i": i + 1,
                "n": n,
                "title": seg.title,
                "duration": round(seg.end - seg.start, 1),
                "pct_overall": round(_map_stage_pct("clips", clip_local_pct), 1),
            })

            try:
                emit({"type": "clip_substep", "i": i + 1, "step": "cut", "label": "Нарезаю"})
                clip_raw = debug_dir / f"clip_{i + 1:02d}_raw.mp4"

                # Multi-source: маппим global timestamps → конкретный файл.
                # Если seg.start и seg.end в разных видео — режем по границе
                # стартового видео (LLM не должен такое выбирать, но защита).
                boundaries = transcript.get("video_boundaries") or []
                if boundaries:
                    src_path, local_start = resolve_source_for_time(seg.start, boundaries)
                    src_path_end, local_end = resolve_source_for_time(
                        max(seg.start, seg.end - 0.001), boundaries
                    )
                    if src_path != src_path_end:
                        # Клип пересекает границу — обрезаем до конца стартового
                        for b in boundaries:
                            if Path(b["path"]) == src_path:
                                local_end = b["duration"]
                                break
                        log.warning(
                            f"Клип {i + 1} пересекал границу видео — "
                            f"обрезан до конца {src_path.name}"
                        )
                    cut_segment(src_path, local_start, local_end, clip_raw)
                    # Запоминаем для subtitle/meta
                    seg.__dict__["_source_path"] = str(src_path)
                    seg.__dict__["_local_start"] = local_start
                    seg.__dict__["_local_end"] = local_end
                else:
                    cut_segment(video, seg.start, seg.end, clip_raw)

                if not clip_raw.exists() or clip_raw.stat().st_size < 1000:
                    log.warning(f"Клип {i + 1} пустой, пропускаю")
                    failed.append({"i": i + 1, "title": seg.title, "reason": "empty raw clip"})
                    emit({"type": "clip_failed", "i": i + 1, "title": seg.title,
                          "reason": "empty raw clip"})
                    continue

                current = clip_raw

                # Опционально: вырезаем длинные тишины.
                # Ошибка silence_cut НЕ должна валить клип — пропускаем шаг.
                if cut_silences:
                    emit({"type": "clip_substep", "i": i + 1, "step": "silence",
                          "label": "Убираю длинные паузы"})
                    clip_nosil = debug_dir / f"clip_{i + 1:02d}_nosil.mp4"
                    try:
                        _, sil_stats = remove_silences(
                            current, clip_nosil, cfg,
                            noise_threshold_db=silence_threshold_db,
                            min_silence_sec=silence_min_sec,
                            keep_padding_sec=silence_padding_sec,
                        )
                        # Используем результат если убрано хотя бы 0.15с —
                        # иначе nosil-файл идентичен оригиналу или почти.
                        min_final_after_silence = max(
                            float(cfg["shorts"].get("min_duration_sec", 15)),
                            float(cfg["shorts"].get("target_duration_sec", 35))
                            * float(cfg["shorts"].get("silence_cut_min_final_ratio", 0.8)),
                        )
                        if (
                            sil_stats["removed_sec"] > 0.15
                            and clip_nosil.exists()
                            and sil_stats["final_sec"] >= min_final_after_silence
                        ):
                            current = clip_nosil
                            log.info(
                                f"  → Применён silence-cut: "
                                f"{sil_stats['original_sec']:.1f}с → "
                                f"{sil_stats['final_sec']:.1f}с "
                                f"(минус {sil_stats['removed_sec']:.1f}с)"
                            )
                        elif (
                            sil_stats["removed_sec"] > 0.15
                            and clip_nosil.exists()
                            and sil_stats["final_sec"] < min_final_after_silence
                        ):
                            log.warning(
                                f"silence-cut пропущен на клипе {i + 1}: "
                                f"{sil_stats['original_sec']:.1f}с → "
                                f"{sil_stats['final_sec']:.1f}с ниже лимита "
                                f"{min_final_after_silence:.1f}с"
                            )
                    except Exception as sil_err:
                        log.warning(
                            f"silence_cut упал на клипе {i + 1}, "
                            f"продолжаю с оригиналом: {sil_err}"
                        )

                emit({"type": "clip_substep", "i": i + 1, "step": "reframe",
                      "label": f"Вертикализация ({reframe_mode})"})
                clip_vert = debug_dir / f"clip_{i + 1:02d}_vert.mp4"
                reframe(current, clip_vert, reframe_mode, cfg)

                current = clip_vert

                # Опционально: тонкий цветокор для уникализации.
                # Ошибка не валит клип — пропускаем шаг.
                if color_grade:
                    emit({"type": "clip_substep", "i": i + 1, "step": "color",
                          "label": "Тонкий цветокор (уникализация)"})
                    clip_color = debug_dir / f"clip_{i + 1:02d}_color.mp4"
                    try:
                        apply_color_grade(
                            current, clip_color, cfg,
                            seed_key=f"{job_id}_{i + 1}",
                        )
                        current = clip_color
                    except Exception as col_err:
                        log.warning(
                            f"color_grade упал на клипе {i + 1}, "
                            f"продолжаю с предыдущим: {col_err}"
                        )

                if add_subtitles:
                    emit({"type": "clip_substep", "i": i + 1, "step": "subtitle",
                          "label": "Запекаю субтитры"})
                    ass_path = debug_dir / f"clip_{i + 1:02d}.ass"
                    build_ass(
                        transcript.get("word_segments", []),
                        ass_path, cfg, seg.start, seg.end,
                        transcript_segments=transcript.get("segments", []),
                    )
                    clip_sub = debug_dir / f"clip_{i + 1:02d}_sub.mp4"
                    burn_subtitles(current, ass_path, clip_sub, cfg)
                    current = clip_sub

                # Vocal isolation: убираем оригинальный score сериала
                if cfg.get("safety", {}).get("vocal_isolation_enabled", False):
                    emit({"type": "clip_substep", "i": i + 1, "step": "vocal_isolation",
                          "label": "Изолирую голос от музыки (demucs)"})
                    current = isolate_vocals(current, debug_dir / f"clip_{i + 1:02d}_vi", cfg)

                clip_final = shorts_dir / f"clip_{i + 1:02d}.mp4"
                # Приоритет: AI-сгенерированная музыка > файлы из music/<mood>/
                music_to_use = chosen_music or (
                    pick_music(seg.music_mood, music_dir) if add_music else None
                )
                if music_to_use:
                    emit({"type": "clip_substep", "i": i + 1, "step": "audio",
                          "label": "Подмешиваю музыку"})
                    mix_with_music(
                        current, music_to_use, clip_final, cfg,
                        music_volume_override=music_volume,
                    )
                else:
                    shutil.copy(current, clip_final)

                clip_record = {
                    "file": str(clip_final.relative_to(out_dir)),
                    "title": seg.title,
                    "description": seg.description,
                    "tags": seg.tags,
                    "music_mood": seg.music_mood,
                    "duration": round(seg.end - seg.start, 2),
                    "source_path": seg.__dict__.get("_source_path"),
                    "source_start": seg.__dict__.get("_local_start"),
                    "source_end": seg.__dict__.get("_local_end"),
                }

                # --- Rights manifest: аудит-документ источников ---
                # Полезно для disputing Content ID если YouTube жалуется.
                safety_cfg = cfg.get("safety", {})
                if safety_cfg.get("write_rights_manifest", True):
                    src_path = seg.__dict__.get("_source_path") or ""
                    src_name = Path(src_path).name if src_path else "unknown"
                    music_rights, ai_music_disclosure, ai_music_reason = _music_rights_info(
                        music_to_use, chosen_music, seg.music_mood, cfg
                    )
                    manifest = {
                        "clip_index": i + 1,
                        "clip_title": seg.title,
                        "source": {
                            "video_file": src_name,
                            "license_status": "third_party_unverified",
                            "warning": (
                                "Источник — стороннее видео без лицензии. "
                                "Content ID может матчить оригинальный score. "
                                "Возможны 'No restriction' claims."
                            ),
                        },
                        "audio_in_output": {
                            "original_dialogue": True,
                            "original_score_bleeds_through": True,
                            "background_music": music_rights,
                        },
                        "visual_edits": [
                            "smart_reframe_9x16",
                            "subtle_color_grade",
                            "subtitle_overlay_karaoke",
                            "silence_cut",
                        ],
                        "ai_disclosure_required": ai_music_disclosure,
                        "ai_disclosure_reason": ai_music_reason,
                        "compliance_notes": [
                            "Safety-фильтр исключает intro/outro/silence",
                            "Не используется pitch/speed уникализация (запрещено YouTube)",
                        ],
                    }
                    manifest_path = out_dir / "rights" / f"clip_{i + 1:02d}_rights.json"
                    manifest_path.parent.mkdir(parents=True, exist_ok=True)
                    manifest_path.write_text(
                        json.dumps(manifest, ensure_ascii=False, indent=2),
                        encoding="utf-8",
                    )
                    clip_record["rights_manifest"] = str(
                        manifest_path.relative_to(out_dir)
                    )

                # --- Platform metadata (generated once, adapted per platform) ---
                seo_meta = None
                yt_ready = bool(youtube_upload and yt_is_authorized())
                tt_ready = bool(tiktok_upload and tt_is_authorized())
                if yt_ready or tt_ready:
                    emit({"type": "clip_substep", "i": i + 1,
                          "step": "seo", "label": "Генерирую SEO-метаданные"})
                    seo_meta = generate_seo(
                        cfg,
                        clip_title=seg.title,
                        clip_description=seg.description,
                        clip_hook=getattr(seg, "hook", ""),
                        clip_tags_hint=seg.tags or [],
                        music_mood=seg.music_mood,
                        source_context=youtube_source_context,
                        language=cfg.get("whisper", {}).get("language", "ru"),
                    )

                # --- YouTube auto-upload (опционально) ---
                if youtube_upload and yt_ready and seo_meta is not None:
                    try:
                        meta_video = replace(
                            seo_meta,
                            privacy_status=youtube_privacy,
                        )

                        # AI disclosure отключён по умолчанию — упоминание ИИ
                        # в описании вредит продвижению. Включается через
                        # safety.ai_disclosure_in_description если нужно.
                        safety_cfg = cfg.get("safety", {})
                        if safety_cfg.get("ai_disclosure_in_description", False):
                            disclosure = safety_cfg.get(
                                "ai_disclosure_text",
                                "🤖 AI-assisted edit",
                            )
                            if disclosure and disclosure not in meta_video.description:
                                meta_video.description = (
                                    meta_video.description.rstrip()
                                    + f"\n\n---\n{disclosure}"
                                )

                        clip_record["youtube_meta"] = {
                            "title": meta_video.title,
                            "description": meta_video.description,
                            "tags": meta_video.tags,
                            "category_id": meta_video.category_id,
                        }

                        emit({"type": "clip_substep", "i": i + 1,
                              "step": "upload",
                              "label": "Загружаю на YouTube"})

                        def _up_cb(pct: float, _i=i + 1) -> None:
                            emit({"type": "clip_substep", "i": _i,
                                  "step": "upload",
                                  "label": f"YouTube upload {pct:.0f}%"})

                        result: UploadResult = yt_upload_clip(
                            clip_final, meta_video, progress_cb=_up_cb
                        )
                        clip_record["youtube_url"] = result.url
                        clip_record["youtube_video_id"] = result.video_id
                        log.info(f"Клип {i+1} опубликован: {result.url}")
                    except QuotaExceeded as qe:
                        # Дневной лимит — больше не пытаемся в этом джобе.
                        # Помечаем все ПОСЛЕДУЮЩИЕ клипы тоже как пропущенные.
                        log.warning(f"YouTube квота кончилась на клипе {i+1}: {qe}")
                        clip_record["youtube_error"] = f"quota_exceeded: {qe}"
                        clip_record["youtube_skipped_by_quota"] = True
                        # Отключаем upload для оставшихся клипов джоба
                        youtube_upload = False
                        emit({"type": "youtube_quota_exceeded",
                              "i": i + 1, "reason": str(qe)})
                    except AuthRequired as ae:
                        # Токен мёртв — нет смысла ретраить, отключаем upload
                        # для всех оставшихся клипов этого джоба.
                        log.warning(f"YouTube auth dead на клипе {i+1}: {ae}")
                        clip_record["youtube_error"] = f"auth_required: {ae}"
                        clip_record["youtube_skipped_by_auth"] = True
                        youtube_upload = False
                        emit({"type": "youtube_auth_required",
                              "i": i + 1, "reason": str(ae)})
                    except Exception as up_exc:  # noqa: BLE001
                        log.warning(
                            f"YouTube-загрузка клипа {i+1} упала: {up_exc}"
                        )
                        clip_record["youtube_error"] = str(up_exc)
                elif youtube_upload and not yt_is_authorized():
                    log.warning(
                        f"YouTube upload включён, но нет авторизации — "
                        f"клип {i+1} НЕ загружен. Авторизуйся через UI."
                    )
                    clip_record["youtube_error"] = "not authorized"

                # --- TikTok auto-upload (опционально) ---
                if tiktok_upload and tt_ready and seo_meta is not None:
                    try:
                        tiktok_meta = adapt_metadata_for_tiktok(seo_meta, cfg)
                        tiktok_meta.privacy_level = tiktok_privacy
                        tiktok_meta.disable_comment = tiktok_disable_comment
                        tiktok_meta.disable_duet = tiktok_disable_duet
                        tiktok_meta.disable_stitch = tiktok_disable_stitch
                        tiktok_meta.is_aigc = tiktok_is_aigc

                        clip_record["tiktok_meta"] = {
                            "caption": tiktok_meta.caption,
                            "privacy_level": tiktok_meta.privacy_level,
                            "disable_comment": tiktok_meta.disable_comment,
                            "disable_duet": tiktok_meta.disable_duet,
                            "disable_stitch": tiktok_meta.disable_stitch,
                            "is_aigc": tiktok_meta.is_aigc,
                        }

                        emit({"type": "clip_substep", "i": i + 1,
                              "step": "upload",
                              "label": "Загружаю в TikTok"})

                        def _tt_cb(pct: float, _i=i + 1) -> None:
                            emit({"type": "clip_substep", "i": _i,
                                  "step": "upload",
                                  "label": f"TikTok upload {pct:.0f}%"})

                        tt_cfg = cfg.get("tiktok", {})
                        result_tt: TikTokUploadResult = tt_upload_clip(
                            clip_final,
                            tiktok_meta,
                            progress_cb=_tt_cb,
                            poll_timeout_sec=float(
                                tt_cfg.get("status_poll_timeout_sec", 45)
                            ),
                            poll_interval_sec=float(
                                tt_cfg.get("status_poll_interval_sec", 5)
                            ),
                        )
                        clip_record["tiktok_publish_id"] = result_tt.publish_id
                        clip_record["tiktok_status"] = result_tt.status
                        if result_tt.public_post_ids:
                            clip_record["tiktok_public_post_ids"] = (
                                result_tt.public_post_ids
                            )
                        log.info(
                            f"Клип {i+1} отправлен в TikTok: "
                            f"{result_tt.publish_id} status={result_tt.status}"
                        )
                    except TikTokAuthRequired as ae:
                        log.warning(f"TikTok auth dead на клипе {i+1}: {ae}")
                        clip_record["tiktok_error"] = f"auth_required: {ae}"
                        clip_record["tiktok_skipped_by_auth"] = True
                        tiktok_upload = False
                        emit({"type": "tiktok_auth_required",
                              "i": i + 1, "reason": str(ae)})
                    except Exception as tt_exc:  # noqa: BLE001
                        log.warning(
                            f"TikTok-загрузка клипа {i+1} упала: {tt_exc}"
                        )
                        clip_record["tiktok_error"] = str(tt_exc)
                elif tiktok_upload and not tt_is_authorized():
                    log.warning(
                        f"TikTok upload включён, но нет авторизации — "
                        f"клип {i+1} НЕ загружен. Авторизуйся через UI."
                    )
                    clip_record["tiktok_error"] = "not authorized"

                clip_results.append(clip_record)
                emit({
                    "type": "clip_done",
                    "i": i + 1,
                    "title": seg.title,
                    "file": str(clip_final.relative_to(out_dir)),
                    "duration": round(seg.end - seg.start, 2),
                    "youtube_url": clip_record.get("youtube_url"),
                    "tiktok_publish_id": clip_record.get("tiktok_publish_id"),
                    "tiktok_status": clip_record.get("tiktok_status"),
                })
            except Exception as exc:  # noqa: BLE001
                log.exception(f"Клип {i + 1} '{seg.title}' упал: {exc}")
                failed.append({"i": i + 1, "title": seg.title, "reason": str(exc)})
                emit({"type": "clip_failed", "i": i + 1, "title": seg.title,
                      "reason": str(exc)})
                continue

        if not clip_results:
            raise RuntimeError(
                f"Ни одного клипа не отрендерено. Упало: {len(failed)}."
            )

        # === ШАГ 6: Финализация ===
        stage("finalize", "Сохраняю мета-данные", 0)
        meta = {
            "job_id": job_id,
            "source": sources_list[0] if len(sources_list) == 1 else sources_list,
            "sources": sources_list,
            "reframe_mode": reframe_mode,
            "clips": clip_results,
            "failed": failed,
            "video_duration_sec": video_duration,
            "total_time_sec": round(time.monotonic() - job_start, 1),
            "video_boundaries": transcript.get("video_boundaries", []),
        }
        (out_dir / "meta.json").write_text(
            json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        stage("finalize", f"Готово! Создано {len(clip_results)} клипов", 100)
        emit({"type": "done", "meta": meta})
        return meta

    except Exception as exc:
        emit({"type": "error", "message": str(exc)})
        raise
